export const DEFAULT_PERMISSIONS = [
  {
    module: 'admin',
    action: 'view',
    description: 'View founder and platform administration surfaces',
  },
  {
    module: 'analytics',
    action: 'view',
    description: 'View analytics dashboards and reports',
  },
  {
    module: 'dashboard',
    action: 'view',
    description: 'View dashboard summaries',
  },
  { module: 'patients', action: 'view', description: 'View patient records' },
  {
    module: 'patients',
    action: 'create',
    description: 'Create patient records',
  },
  {
    module: 'patients',
    action: 'update',
    description: 'Update patient records',
  },
  {
    module: 'patients',
    action: 'delete',
    description: 'Archive patient records',
  },
  {
    module: 'appointments',
    action: 'view',
    description: 'View appointment schedules',
  },
  {
    module: 'appointments',
    action: 'create',
    description: 'Create appointments',
  },
  {
    module: 'appointments',
    action: 'update',
    description: 'Update appointments',
  },
  {
    module: 'appointments',
    action: 'delete',
    description: 'Cancel appointments',
  },
  { module: 'queues', action: 'view', description: 'View queue status' },
  { module: 'queues', action: 'update', description: 'Update queue status' },
  {
    module: 'consultations',
    action: 'view',
    description: 'View consultations',
  },
  {
    module: 'consultations',
    action: 'create',
    description: 'Create consultations',
  },
  {
    module: 'consultations',
    action: 'update',
    description: 'Update consultations',
  },
  {
    module: 'prescriptions',
    action: 'view',
    description: 'View prescriptions',
  },
  {
    module: 'prescriptions',
    action: 'create',
    description: 'Create prescriptions',
  },
  {
    module: 'documents',
    action: 'view',
    description: 'View uploaded medical documents',
  },
  {
    module: 'documents',
    action: 'upload',
    description: 'Upload medical documents',
  },
  {
    module: 'follow_ups',
    action: 'view',
    description: 'View follow-up records',
  },
  {
    module: 'follow_ups',
    action: 'create',
    description: 'Create follow-up records',
  },
  {
    module: 'follow_ups',
    action: 'update',
    description: 'Update follow-up records',
  },
  { module: 'billing', action: 'view', description: 'View billing dashboards' },
  { module: 'invoices', action: 'view', description: 'View invoices' },
  { module: 'invoices', action: 'create', description: 'Create invoices' },
  { module: 'payments', action: 'view', description: 'View payments' },
  { module: 'payments', action: 'create', description: 'Record payments' },
  {
    module: 'communications',
    action: 'view',
    description: 'View communication center',
  },
  {
    module: 'messages',
    action: 'send',
    description: 'Send patient communications',
  },
  { module: 'feedback', action: 'view', description: 'View internal feedback' },
  {
    module: 'feedback',
    action: 'create',
    description: 'Create internal feedback',
  },
  {
    module: 'reviews',
    action: 'view',
    description: 'View reviews and referrals',
  },
  { module: 'tasks', action: 'view', description: 'View tasks' },
  { module: 'tasks', action: 'create', description: 'Create tasks' },
  { module: 'tasks', action: 'update', description: 'Update tasks' },
  { module: 'tasks', action: 'delete', description: 'Cancel tasks' },
  { module: 'settings', action: 'view', description: 'View settings' },
  {
    module: 'settings',
    action: 'branding',
    description: 'Manage clinic branding settings',
  },
  { module: 'users', action: 'view', description: 'View staff users' },
  { module: 'roles', action: 'view', description: 'View roles' },
  { module: 'permissions', action: 'view', description: 'View permissions' },
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  'Super Admin': DEFAULT_PERMISSIONS.map(
    (permission) => `${permission.module}.${permission.action}`,
  ),
  'Organization Owner': DEFAULT_PERMISSIONS.map(
    (permission) => `${permission.module}.${permission.action}`,
  ),
  'Clinic Admin': DEFAULT_PERMISSIONS.filter(
    (permission) =>
      !(permission.module === 'admin' && permission.action === 'view'),
  ).map((permission) => `${permission.module}.${permission.action}`),
  'Branch Manager': [
    'dashboard.view',
    'analytics.view',
    'patients.view',
    'patients.create',
    'patients.update',
    'appointments.view',
    'appointments.create',
    'appointments.update',
    'queues.view',
    'queues.update',
    'consultations.view',
    'consultations.create',
    'consultations.update',
    'prescriptions.view',
    'documents.view',
    'documents.upload',
    'follow_ups.view',
    'follow_ups.update',
    'billing.view',
    'invoices.view',
    'communications.view',
    'feedback.view',
    'tasks.view',
    'tasks.update',
    'settings.view',
    'users.view',
    'roles.view',
    'permissions.view',
  ],
  Doctor: [
    'dashboard.view',
    'analytics.view',
    'patients.view',
    'appointments.view',
    'appointments.update',
    'queues.view',
    'consultations.view',
    'consultations.create',
    'consultations.update',
    'prescriptions.view',
    'prescriptions.create',
    'documents.view',
    'documents.upload',
    'follow_ups.view',
    'follow_ups.create',
    'follow_ups.update',
    'communications.view',
    'feedback.view',
    'feedback.create',
    'tasks.view',
    'tasks.create',
    'tasks.update',
  ],
  Receptionist: [
    'dashboard.view',
    'patients.view',
    'patients.create',
    'patients.update',
    'appointments.view',
    'appointments.create',
    'appointments.update',
    'queues.view',
    'queues.update',
    'documents.view',
    'follow_ups.view',
    'billing.view',
    'invoices.view',
    'invoices.create',
    'payments.view',
    'payments.create',
    'communications.view',
    'messages.send',
    'feedback.view',
    'feedback.create',
    'tasks.view',
  ],
  Nurse: [
    'patients.view',
    'appointments.view',
    'queues.view',
    'queues.update',
    'consultations.view',
    'documents.view',
    'documents.upload',
    'follow_ups.view',
    'follow_ups.update',
    'tasks.view',
    'tasks.create',
    'tasks.update',
  ],
  Accountant: [
    'dashboard.view',
    'analytics.view',
    'billing.view',
    'invoices.view',
    'invoices.create',
    'payments.view',
    'payments.create',
    'feedback.view',
  ],
  Patient: ['prescriptions.view', 'documents.view', 'follow_ups.view'],
};
